#:schema https://docs.cocogitto.io/cog-schema.json
# For a reference of possible values: https://docs.cocogitto.io/config/

# A list of command to run AFTER creating a version.
# `{{version}}` will be interpreted as your target version
# `{{version_tag}}` includes the version and the `tag_prefix`
post_bump_hooks = [
    # Re-tag release commit to ensure a signed tag
    "git tag {{version_tag}} {{version_tag}}^{} --force --sign --annotate --message='Release {{version}}'"
]

tag_prefix = "v"

[changelog]
path = "CHANGELOG.md"
template = "remote"
remote = "github.com"
owner = "gordon-code"
repository = "jijna2-git-dir"
authors = [
    { signature = "Will Gordon", username = "wgordon17" },
]
